<?php session_start(); ?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Guess My Number</title>      
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="keyword" content="PHP, 'Guess My Number', 'Github Project', ConsonanceNg">
        <meta name="description" content="This PHP program enables the user to guess the number generated by the computer">
        <meta name="author" content="Moses Ajireloja">
        <link rel="stylesheet" href="style.css" type="text/css" media="all">
    </head>  
    <body>
        <div id="container">
        <h2 class="title">GUESS MY NUMBER</h2>
        <p class="welcome">Welcome to this platform. The computer will generate a number between 1 and 100.
        Can you guess what the number is? Let the game begin!        </p>
        <!-- Display the Input Form by default -->
            <form action="index.php" method="post" class="form">
                Enter Your Number:
                <input type="number" name="figure" min="1" max="100" required="required" title="Enter a number between 1 and 100"><br>
                <input type="submit" name="submit" value="Submit and Check" class="button">
                <input type="reset" name="Reset"  value="Reset Number" class="button">
            </form>
            
            <div id="result">
        <?php
          // The computer generates a number and stores it in session.
                    if (!isset($_SESSION['compfigure']) || empty($_SESSION['compfigure'])) {                    
                        $compfigure = rand(1, 100);
                        $_SESSION['compfigure'] = $compfigure;
                    }
                    else {
                        $compfigure = "{$_SESSION['compfigure']}";
                    }
                    
        // Validate the user's input and compare the user's input with the generated number.
            if (isset($_POST['submit'])) {
                // Ensure that a number has been entered.
                if (isset($_POST['figure']) && !empty($_POST['figure']) && is_numeric($_POST['figure'])) {

                    // Then obtain the user's number.
                    $figure = htmlentities(trim($_POST['figure']));
                    
                    if ($figure > 0 && $figure < 101) {
                        
                    // This is the computer's number
                       // echo $compfigure;
                       
                       
                    // Display this if the user's number is lower than the generated number.
                    if ($figure < $compfigure) {
                          echo "<p class=\"title\">Hmm... You're almost there! Try a higher number.</p>";
                          echo "<p>" . "Your Guess: {$figure}" . "</p>";
                          echo "<p>" . "Computer's number is greater than {$figure}." . "</p>";
                          echo "<p>" . "Please try again." . "</p>";
                    }
                    // Display this if the user's number is greater than the generated number.
                    if ($figure > $compfigure) {
                          echo "<p class=\"title\">Oh... That number is too high! Try a lower one.</p>";
                          echo "<p>" . "Your Guess: {$figure}" . "</p>";
                          echo "<p>" . "Computer's number is less than {$figure}." . "</p>";
                          echo "<p>" . "Please try again." . "</p>";
                    }
                   
                    if ($figure == $compfigure) {
                          echo "<p class=\"title\">Awesome! You deserve a round of applause.</p>";
                          echo "<p>" . "Your Guess: {$figure}" . "</p>";
                          echo "<p>" . "Computer's Number: {$compfigure}" . "</p>";
                          echo "<p>" . "Remark: Accurate Guess!" . "</p>";
                          echo "<center><a href=\"refresh.php\" class=\"refresh\">START AGAIN</a></center>";
                    }
                 
                    
                } else {
                    // The number must be between 1 and 100.
                    echo "<p>Sorry, something went wrong.</p>";
                    echo "<p>Please enter a number that is a minimum of 1 and maximum of 100.</p>";
                    echo "<p>Thank you.</p>";
                }
                
                }
                else {
                    // Notify user to enter a value and then submit.
                    echo "<p>Sorry, something went wrong.</p>";
                    echo "<p>Please enter a valid number.</p>";
                    echo "<p>Thank you.</p>";
                }
            } 
        ?>
        </div>
        </div>
    </body>
</html>
