<?php

class GuessMyNumber{
    /*
    *
    *   Computer randomly generate a number
    *   Collect user input
    *   Output High if input is higher than the generated number
    *   Output Low if input is less than generated number
    *   Output Guess right if its the same number 
    *
    *   @param int $input_number Thats the user input
    */
    public static function guess(int $input_numb)
    {
        $computer_random_number = rand(1, 1000);
        $result = "";
        if($input_numb == $computer_random_number)
        {
            $result = "You Guess right: <br>Your Input Number is:  ".$input_numb."<br> Random Number generated by the system is:  ".$computer_random_number; 
        }
        elseif($input_numb > $computer_random_number)
        {
            $result = "You are too high on your guess <br> Your Input Number is  ".$input_numb;
        }
        else{
            $result = "You are too low on your guess <br> Your Input Number is  ".$input_numb;
        }
        return $result;
    }
}

$number = $_POST['user_input'];
$show_result = GuessMyNumber::guess($number);
echo $show_result."<p><button onclick="."location.href='index.html'>Back</button>";

